# Generated by Django 4.0.2 on 2022-02-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie__app', '0002_alter_movie_director_alter_review_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.TimeField(),
        ),
    ]
