# Generated by Django 4.0.2 on 2022-02-16 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie__app', '0003_alter_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='movie__app.movie'),
        ),
    ]
