# Generated by Django 4.0.2 on 2022-02-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie__app', '0008_stars_alter_review_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
        migrations.DeleteModel(
            name='Stars',
        ),
    ]
