# Generated by Django 4.0.2 on 2022-02-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie__app', '0011_remove_movie_stars_remove_review_stars_review_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='value',
            new_name='stars',
        ),
    ]
